# Generated by Django 4.2.1 on 2023-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='dealitem',
            options={'verbose_name': 'Содержимое сделки', 'verbose_name_plural': 'Содержимое сделки'},
        ),
        migrations.AlterModelOptions(
            name='reviewlot',
            options={'verbose_name': 'Отзыв к лоту', 'verbose_name_plural': 'Отзывы к лотам'},
        ),
        migrations.AlterModelOptions(
            name='reviewseller',
            options={'verbose_name': 'Отзыв на продавца', 'verbose_name_plural': 'Отзывы на продавцов'},
        ),
        migrations.AddField(
            model_name='dealitem',
            name='price',
            field=models.IntegerField(default=1, help_text='Укажите цену сделки', verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
